{
  description = "Zellij with right-click to close tabs (patched binary + tab-bar plugin)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    {
      self,
      nixpkgs,
      rust-overlay,
      flake-utils,
    }:
    # eachDefaultSystem includes x86_64-darwin; nixpkgs-unstable dropped it (26.11+).
    flake-utils.lib.eachSystem [ "x86_64-linux" "aarch64-linux" "aarch64-darwin" ] (
      system:
      let
        pkgs = import nixpkgs {
          inherit system;
          overlays = [ (import rust-overlay) ];
        };
        inherit (pkgs) lib;

        # Stock zellij patched so unselectable plugins (tab bar) receive right-clicks.
        zellij-unwrapped = pkgs.zellij-unwrapped.overrideAttrs (old: {
          pname = "zellij-unwrapped-rightclick";
          patches = (old.patches or [ ]) ++ [
            ./patches/zellij-right-click-unselectable.patch
          ];
        });

        zellij = pkgs.zellij.override { inherit zellij-unwrapped; };

        rustWasm = pkgs.rust-bin.stable.latest.default.override {
          targets = [ "wasm32-wasip1" ];
        };

        rustPlatformWasm = pkgs.makeRustPlatform {
          cargo = rustWasm;
          rustc = rustWasm;
        };

        tab-bar-right-close = rustPlatformWasm.buildRustPackage {
          pname = "zellij-tab-bar-right-close";
          version = "0.1.0";
          src = ./tab-bar;

          cargoLock.lockFile = ./tab-bar/Cargo.lock;

          doCheck = false;

          # buildRustPackage defaults to host triple; we only want the wasm artifact.
          buildPhase = ''
            runHook preBuild
            cargo build --release --target wasm32-wasip1 -j "$NIX_BUILD_CORES"
            runHook postBuild
          '';

          installPhase = ''
            runHook preInstall
            mkdir -p "$out/share/zellij/plugins"
            cp target/wasm32-wasip1/release/tab-bar-right-close.wasm \
              "$out/share/zellij/plugins/tab-bar-right-close.wasm"
            runHook postInstall
          '';
        };

        wasmPath = "${tab-bar-right-close}/share/zellij/plugins/tab-bar-right-close.wasm";

        # Minimal config: only overrides the tab-bar plugin alias. Other options
        # (keybinds, themes, …) stay at Zellij defaults unless the user passes
        # their own --config / ZELLIJ_CONFIG_*.
        configKdl = pkgs.writeText "zellij-right-click-tab.kdl" ''
          // Generated by the zellij-right-click-tab flake.
          // Right-click a tab to close; double-click empty tab-bar space for a new tab.
          plugins {
              tab-bar location="file:${wasmPath}"
          }
        '';

        # Wrapper so `nix run` / default package use patched binary + config.
        zellij-wrapped = pkgs.writeShellApplication {
          name = "zellij";
          text = ''
            # If the caller already chose a config, do not override it.
            if [ -n "''${ZELLIJ_CONFIG_FILE:-}" ] || [ -n "''${ZELLIJ_CONFIG_DIR:-}" ]; then
              exec ${lib.getExe zellij} "$@"
            fi
            for arg in "$@"; do
              case "$arg" in
                -c|--config|--config-dir)
                  exec ${lib.getExe zellij} "$@"
                  ;;
              esac
            done
            exec ${lib.getExe zellij} --config ${configKdl} "$@"
          '';
          meta = {
            description = "Patched Zellij with right-click tab close and double-click new tab";
            mainProgram = "zellij";
          };
        };

        # Full install: wrapper + wasm + config file in share/
        with-plugin = pkgs.symlinkJoin {
          name = "zellij-right-click-tab";
          paths = [
            zellij-wrapped
            tab-bar-right-close
          ];
          postBuild = ''
            mkdir -p "$out/share/zellij"
            cp ${configKdl} "$out/share/zellij/config.kdl"
            cat > "$out/share/zellij/config-snippet.kdl" <<EOF
            // Merge into ~/.config/zellij/config.kdl if you use a custom config:
            tab-bar location="file:${wasmPath}"
            EOF
          '';
          meta = {
            description = "Patched Zellij + tab-bar plugin: right-click closes tabs";
            mainProgram = "zellij";
          };
        };
      in
      {
        packages = {
          default = with-plugin;
          zellij = zellij-wrapped;
          zellij-unwrapped = zellij-unwrapped;
          zellij-bin = zellij; # bare patched binary, no config wrapper
          tab-bar-right-close = tab-bar-right-close;
          with-plugin = with-plugin;
          config = configKdl;
        };

        apps.default = {
          type = "app";
          program = "${zellij-wrapped}/bin/zellij";
        };

        devShells.default = pkgs.mkShell {
          packages = [
            rustWasm
            zellij-wrapped
          ];
          shellHook = ''
            echo "zellij-right-click-tab"
            echo "  nix run .                 # patched zellij + flake config"
            echo "  nix build .#tab-bar-right-close"
          '';
        };

        checks.zellij = zellij-wrapped;
        checks.tab-bar-right-close = tab-bar-right-close;
      }
    )
    // {
      overlays.default = final: prev: {
        zellij-right-click-tab = self.packages.${prev.stdenv.hostPlatform.system}.default;
        zellij = self.packages.${prev.stdenv.hostPlatform.system}.zellij;
      };

      homeModules.default =
        {
          config,
          lib,
          pkgs,
          ...
        }:
        let
          inherit (lib)
            mkEnableOption
            mkIf
            mkOption
            types
            ;
          cfg = config.programs.zellij-right-click-tab;
          sys = pkgs.stdenv.hostPlatform.system;
          flakePkgs = self.packages.${sys};
        in
        {
          options.programs.zellij-right-click-tab = {
            enable = mkEnableOption "Zellij with right-click to close tabs";

            package = mkOption {
              type = types.package;
              default = flakePkgs.default;
              defaultText = lib.literalExpression "self.packages.\${system}.default";
              description = "Package providing wrapped zellij + plugin (default) or bare binary.";
            };

            tabBarPackage = mkOption {
              type = types.package;
              default = flakePkgs.tab-bar-right-close;
              defaultText = lib.literalExpression "self.packages.\${system}.tab-bar-right-close";
              description = "Package providing tab-bar-right-close.wasm.";
            };

            # When true, also write plugins alias into xdg config for non-wrapper use.
            installUserConfigSnippet = mkOption {
              type = types.bool;
              default = true;
              description = "Install right-click-tab.kdl under xdg config for merging into config.kdl.";
            };
          };

          config = mkIf cfg.enable {
            home.packages = [ cfg.package ];

            xdg.configFile."zellij/plugins/tab-bar-right-close.wasm".source =
              "${cfg.tabBarPackage}/share/zellij/plugins/tab-bar-right-close.wasm";

            xdg.configFile."zellij/right-click-tab.kdl" = lib.mkIf cfg.installUserConfigSnippet {
              text = ''
                // Generated by programs.zellij-right-click-tab
                // Merge the plugins block into config.kdl if you do not use the wrapped binary.
                plugins {
                    tab-bar location="file:${config.xdg.configHome}/zellij/plugins/tab-bar-right-close.wasm"
                }
              '';
            };
          };
        };
    };
}
